In [190]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [169]:
df = pd.read_csv('hiring.csv')
df

experience  test  interview  salary
0        NaN   8.0          9   50000
1        NaN   8.0          6   45000
2       five   6.0          7   60000
3        two  10.0         10   65000
4      seven   9.0          6   70000
5      three   7.0         10   62000
6        ten   NaN          7   72000
7     eleven   7.0          8   80000

In [170]:
#function
def word_to_num(text):
    units = {
        'zero' : 0, 'one' : 1, 'two' : 2, 'three': 3, 'four': 4, 'five': 5,
        'six': 6, 'seven' : 7, 'eight' : 8, 'nine' : 9, 'ten' : 10,  'NaN': 0,
        'eleven' : 11, 'twelve' : 12, 'thirteen' : 13, 'fourteen': 14, 'fifteen': 15,
        'sixteen': 16, 'seventeen' : 17, 'eighteen' : 18, 'nineteen' : 19
    }
    tens = {
        'twenty' : 20, 'thirty': 30, 'forty': 40, 'fifty': 50,
        'sixty': 60, 'seventy' : 70, 'eighty' : 80, 'ninety' : 90,
    }
    text = text.lower().replace('-',' ').replace('and', '')
    words = text.split()
    
    total = 0
    current = 0
    for word in words:
        if word in units:
            current = current + units[word]
        elif word in tens:
            current = current + tens[word]
        elif word == 'hundred':
            current = current * 100
        elif word == 'thousand':
            current = current * 1000
            total = total + current
    

    return total + current

word_to_num('forty-five')

45

In [171]:
def text2num(text):
    nums = {
        'zero' : 0, 'one' : 1, 'two' : 2, 'three': 3, 'four': 4, 'five': 5,
        'six': 6, 'seven' : 7, 'eight' : 8, 'nine' : 9, 'ten' : 10,  'NaN': 0,
        'eleven' : 11, 'twelve' : 12, 'thirteen' : 13, 'fourteen': 14, 'fifteen': 15,
        'sixteen': 16, 'seventeen' : 17, 'eighteen' : 18, 'nineteen' : 19
    }
    
    result = 0
    if text in nums:
        result = result + nums[text]
    return result

In [172]:
converted_experience = df.experience.apply(text2num)
converted_experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [173]:
df.experience = converted_experience 
df

experience  test  interview  salary
0           0   8.0          9   50000
1           0   8.0          6   45000
2           5   6.0          7   60000
3           2  10.0         10   65000
4           7   9.0          6   70000
5           3   7.0         10   62000
6          10   NaN          7   72000
7          11   7.0          8   80000

In [174]:
import math
test_median = math.floor(df.test.median())
test_median

8

In [175]:
df.test = df.test.fillna(test_median)
df.test

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test, dtype: float64

In [180]:
df

experience  test  interview  salary
0           0   8.0          9   50000
1           0   8.0          6   45000
2           5   6.0          7   60000
3           2  10.0         10   65000
4           7   9.0          6   70000
5           3   7.0         10   62000
6          10   8.0          7   72000
7          11   7.0          8   80000

In [191]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test', 'interview']], df.salary)

LinearRegression()

In [192]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [193]:
reg.intercept_

17737.26346433771

In [198]:
reg.predict([(2, 9, 6)])

C:\Users\HP-PC\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [199]:
2812.95487627 *2 + 1845.70596798 *9 + 2205.24017467 *6 + 17737.26346433771

53205.967976717715

In [200]:
reg.predict([(12, 10, 10)])

C:\Users\HP-PC\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [201]:
2812.95487627 *12 + 1845.70596798 *10 + 2205.24017467 *10 + 17737.26346433771

92002.1834060777